node:
  hosts:
    node1:
      ansible_host: node1
    node2:
      ansible_host: node2
    node3:
      ansible_host: node3
  vars:
    ansible_port: 22
    ansible_ssh_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
devops:
  hosts:
    terraform:
      ansible_host: terraform
      ansible_port: 22
      ansible_ssh_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
